use retail_analytics;
-- Inner Join for Order Details
---  Join orders, order_items, and products to display detailed line items.
select * from products;
select * from  order_items as a
inner join products as b;
-- Total Sales by Store
-- 4 Write a query to group sales (total_price) by each store_id.

 select store_id,sum(total_price) from orders
 inner join order_items
 group by store_id;
 
 --  5 Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.

select product_name, sum(total_price) as sum_total_price  from order_items
group by product_name
order by sum_total_price desc
limit 5;

-- Customer Purchase Summary
-- 6 For each customer, return total orders placed, total items purchased,and total revenue.
select *from order_items;
select first_name, sum(order_id) as total_orders,
sum(order_id) as total_purchased, sum(total_price) as total_revenue
 from customers_dataset
 inner  join order_items
 group by first_name;
 
-- 7. Segment Customers by Total Spend 
--  Write a query to classify customers into spending brackets (e.g., low,medium, high).
select *,
case
when  total_price<= 2000 then " low"
when  total_price between 2000 and 3885 then "medium"
else "high"
end as  classify_customers 
from order_items;

 
-- 8 Staff Performance Analysis
--  Analyze total revenue generated by each staff member based on their handled orders.

select * from ORDERS;
select* from order_items;

select a.staff_id,sum(b.total_price) as total_revenue from orders a
join order_items b
on a.order_id=b.order_id
group by  staff_id;

-- 9 Stock Alert Query
--  Write a query to list products where stock quantity < 10 in any store.

select p.product_name,s.store_id,s.product_id,s.quantity from products p
join stocks s
on p.product_id=s.product_id
where s.quantity <= 10
order by s.quantity desc;


select * from rfm;
































 
 